"""
Generate experiment configs from a base YAML + a sweep profile.

Profiles live in scripts/config_profiles.py — adding a new keyframe-selection
algorithm = adding a function there and registering it in PROFILES.

Usage:
    # list available profiles
    python scripts/gen_configs.py --list

    # generate the NTU-VIRAL eee_03 sweep for the nurbs_lvi selector
    python scripts/gen_configs.py \\
        --base   configs/local/ntu_eee_03_200.yaml \\
        --profile nurbs_lvi \\
        --out-dir configs/local/ntu_eee_03/nurbs_lvi

    # multiple profiles at once, each into its own subdir
    python scripts/gen_configs.py \\
        --base   configs/local/ntu_eee_03_200.yaml \\
        --profile skip_no_filter mapskip vista nurbs_lvi \\
        --out-root configs/local/ntu_eee_03

The base config's output.save_dir is automatically suffixed with the sweep
suffix so each run lands in its own output folder.
"""

from __future__ import annotations

import argparse
import copy
import sys
from pathlib import Path

import yaml

# Make sibling modules importable when invoked from repo root.
sys.path.insert(0, str(Path(__file__).parent))
from config_profiles import PROFILES  # noqa: E402


def deep_merge(base: dict, patch: dict) -> dict:
    """Recursively merge `patch` into a deep copy of `base`."""
    out = copy.deepcopy(base)
    for k, v in patch.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = deep_merge(out[k], v)
        else:
            out[k] = copy.deepcopy(v)
    return out


def derive_output_dir(base_save_dir: str, suffix: str) -> str:
    """`/foo/bar/ntu_eee_03_200/` -> `/foo/bar/ntu_eee_03_200_<suffix>/`."""
    sd = base_save_dir.rstrip("/")
    return f"{sd}_{suffix}/"


def render_profile(base_path: Path, profile_name: str, out_dir: Path,
                   stem: str | None) -> list[Path]:
    if profile_name not in PROFILES:
        raise SystemExit(
            f"Unknown profile '{profile_name}'. "
            f"Known: {sorted(PROFILES)}"
        )
    base = yaml.safe_load(base_path.read_text())
    stem = stem or base_path.stem
    out_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for suffix, patch in PROFILES[profile_name]():
        merged = deep_merge(base, patch)
        if "output" in merged and "save_dir" in merged["output"]:
            merged["output"]["save_dir"] = derive_output_dir(
                merged["output"]["save_dir"], suffix
            )

        out_path = out_dir / f"{stem}_{suffix}.yaml"
        out_path.write_text(
            "# Auto-generated by scripts/gen_configs.py — do not edit by hand.\n"
            f"# base    = {base_path}\n"
            f"# profile = {profile_name}\n"
            f"# suffix  = {suffix}\n\n"
            + yaml.safe_dump(merged, sort_keys=True)
        )
        written.append(out_path)
    return written


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", type=Path, help="base YAML config")
    ap.add_argument("--profile", nargs="*", default=[],
                    help="one or more profile names (see --list)")
    ap.add_argument("--out-dir", type=Path,
                    help="output dir for a single profile")
    ap.add_argument("--out-root", type=Path,
                    help="output root; each profile goes into <root>/<profile>/")
    ap.add_argument("--stem", type=str,
                    help="filename stem (default: base config stem)")
    ap.add_argument("--list", action="store_true",
                    help="list registered profiles and exit")
    args = ap.parse_args()

    if args.list:
        print("Registered profiles:")
        for name, fn in PROFILES.items():
            entries = fn()
            print(f"  {name}  ({len(entries)} configs: "
                  f"{', '.join(s for s, _ in entries[:3])}"
                  f"{'…' if len(entries) > 3 else ''})")
        return

    if not args.base or not args.profile:
        ap.error("--base and at least one --profile are required (or pass --list)")

    if args.out_dir and args.out_root:
        ap.error("Pass either --out-dir or --out-root, not both")
    if not args.out_dir and not args.out_root:
        ap.error("Need --out-dir (single profile) or --out-root (multi)")

    for prof in args.profile:
        if args.out_root:
            target = args.out_root / prof
        else:
            target = args.out_dir
        written = render_profile(args.base, prof, target, args.stem)
        print(f"[{prof}] wrote {len(written)} configs to {target}")


if __name__ == "__main__":
    main()
