#!/usr/bin/env python3
"""Generate a full selector-sweep config tree for ANY amtown03/AGZ slice.

Generalisation of gen_s1000_400f_configs.py / gen_s3100_200f_configs.py: instead
of one hard-coded (start, frames) pair per script, this takes the slice on the
command line and reuses the *identical* selector defaults/variants/folders from
gen_s3100_200f_configs.py (single source of truth, kept in sync with CLAUDE.md).

The per-dataset base template (dataset paths / intrinsic / image_size) is reused
verbatim; only dataset.start_frame, dataset.max_frames, output.save_dir and
fair_eval are overridden. So a new slice is fully described by:

    --dataset {amtown03,agz}  --start <frame>  --frames {200,400}

Output tree mirrors the existing sweeps exactly:
    configs/local/<dataset>/s<start>_<frames>f/<group>/<dataset>_s<start>_<frames>f_<variant>.yaml

and plugs straight into  scripts/run_sweep.sh --slice <dataset>:<start>:<frames>.

Examples (see scripts/run_more_slices.sh for the batch this BA uses):
    python scripts/gen_slice_configs.py --dataset amtown03 --start 5000 --frames 200
    python scripts/gen_slice_configs.py --dataset agz      --start 5600 --frames 200
"""

from __future__ import annotations

import argparse
from pathlib import Path

# Reuse the canonical selector defaults/variants/folders and the patch helpers.
# Importing is side-effect-free (main() is __main__-guarded).
import gen_s3100_200f_configs as g

REPO = Path(__file__).resolve().parents[1]

# Per-dataset base template + fair_eval style. The template carries the dataset
# root / camstamp / gps_csv / intrinsic / image_size; we only override the slice
# window and the output dir below.
DATASET_BASE = {
    "amtown03": {
        "template": REPO / "configs/local/amtown03/s3100_200f/amtown03_short_200_template.yaml",
        "frame_comment": "amtown03",
        "fair_eval": {
            "enabled": True,
            "eval_stride": 10,
            "gt_poses_file": "dji_poses_all_w2c.txt",
            "save_renders": True,
        },
    },
    "agz": {
        # AGZ slices mirror the existing s7950_200f / s2675_400f layout, which
        # uses the minimal fair_eval block (no gt_poses_file -> dataset poses).
        "template": REPO / "configs/local/agz/s7950_200f/amtown03_short_200_template.yaml",
        "frame_comment": "agz (agz_0_10000)",
        "fair_eval": {"enabled": True, "eval_stride": 10},
    },
}


def build_plan(base: dict) -> list[tuple[str, str, dict]]:
    """Same plan as gen_s3100_200f_configs.main(): baseline, mapskip,
    skip_no_filter, then every selector default + its variants."""
    plan: list[tuple[str, str, dict]] = []
    plan.append(("baseline", "vings_filter", g.patch_baseline(base)))
    for n in g.SKIP_VALUES:
        plan.append(("mapskip", f"mapskip_{n}", g.patch_mapskip(base, n)))
    for n in g.SKIP_VALUES:
        plan.append(("skip_no_filter", f"nofilter_skip_{n}",
                     g.patch_skip_no_filter(base, n)))
    for sel, short in g.SELECTOR_FOLDER.items():
        plan.append((short, short, g.patch_selector(base, sel)))
        for suffix, override in g.SELECTOR_VARIANTS.get(sel, {}).items():
            plan.append((short, f"{short}_{suffix}",
                         g.patch_selector(base, sel, override)))
    return plan


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dataset", required=True, choices=sorted(DATASET_BASE))
    ap.add_argument("--start", required=True, type=int, help="start_frame")
    ap.add_argument("--frames", required=True, type=int, help="max_frames (200 or 400)")
    args = ap.parse_args()

    spec = DATASET_BASE[args.dataset]
    template: Path = spec["template"]
    if not template.exists():
        ap.error(f"Base template missing: {template}")

    slug = f"s{args.start}_{args.frames}f"
    name_prefix = f"{args.dataset}_{slug}"
    target_root = REPO / "configs/local" / args.dataset / slug
    save_dir = str(REPO / "output" / f"exp_{args.dataset}_{slug}") + "/"
    end = args.start + args.frames - 1

    with open(template) as f:
        base = g.yaml.full_load(f)
    base.setdefault("dataset", {})
    base["dataset"]["start_frame"] = args.start
    base["dataset"]["max_frames"] = args.frames
    base["output"]["save_dir"] = save_dir
    base["fair_eval"] = spec["fair_eval"]

    plan = build_plan(base)
    print(f"\n=== {name_prefix} — {len(plan)} configs (frames {args.start}..{end}) ===")
    for group, variant, cfg in plan:
        path = target_root / group / f"{name_prefix}_{variant}.yaml"
        header = (
            f"# Auto-generated by scripts/gen_slice_configs.py "
            f"(--dataset {args.dataset} --start {args.start} --frames {args.frames}) — DO NOT EDIT.\n"
            f"# dataset = {spec['frame_comment']} (frames {args.start}..{end})\n"
            f"# group   = {group}\n"
            f"# variant = {variant}\n"
        )
        g.write_yaml(path, cfg, header)
    # Also drop a copy of the (overridden) template next to the tree, matching
    # the existing sweeps which keep amtown03_short_200_template.yaml in-folder.
    tmpl_out = target_root / "amtown03_short_200_template.yaml"
    g.write_yaml(
        tmpl_out, base,
        f"# Base template for {name_prefix} (copy of {template.name} with "
        f"start_frame={args.start}, max_frames={args.frames}).\n"
        f"# Auto-generated by scripts/gen_slice_configs.py — DO NOT EDIT.",
    )
    print(f"  -> {target_root.relative_to(REPO)}/  ({len(plan)} configs + template)")


if __name__ == "__main__":
    main()
