#!/usr/bin/env python3
"""Generate the full_6199f sweep configs for amtown03 (entire sequence).

Mirrors scripts/gen_s1000_400f_configs.py 1:1 — identical selector params,
variants and groups — but over the FULL amtown03 sequence (start_frame=0,
max_frames=6199) instead of the 400-frame slice. Keeping every selector knob
byte-identical is the whole point: it makes the full-run results directly
comparable to the s1000_400f slice. The ONLY differences are:

  * template      → configs/local/amtown03/full_6199f/amtown03_full_6199f_template.yaml
                    (start_frame=0, max_frames=6199)
  * output dir    → output/exp_amtown03_full_6199f/
  * name prefix   → amtown03_full_6199f
  * fair_eval     → eval_stride=20 (vs 10 for the slice) to bound held-out
                    render cost over the ~6200-frame sequence

All SELECTOR_DEFAULTS / SELECTOR_VARIANTS / patch_* / write_yaml logic is
imported from the slice generator so the two stay in lock-step.

Output: configs/local/amtown03/full_6199f/<group>/amtown03_full_6199f_<variant>.yaml
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

# Reuse all selector defaults / variants / patch logic from the slice generator.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_s1000_400f_configs as slice_gen  # noqa: E402


REPO = Path(__file__).resolve().parents[1]
TEMPLATE = REPO / "configs/local/amtown03/full_6199f/amtown03_full_6199f_template.yaml"
TARGET_ROOT = REPO / "configs/local/amtown03/full_6199f"
SAVE_DIR = str(REPO / "output/exp_amtown03_full_6199f") + "/"

NAME_PREFIX = "amtown03_full_6199f"
EVAL_STRIDE = 20  # ~310 held-out frames over 6199 (vs stride 10 for the slice)


def load_template() -> dict:
    with open(TEMPLATE) as f:
        return yaml.full_load(f)


def main() -> None:
    if not TEMPLATE.exists():
        print(f"[FEHLER] Template fehlt: {TEMPLATE}", file=sys.stderr)
        sys.exit(1)

    base = load_template()
    # Guard: der tracker-seitige Langzeit-Buffer (depth_video.py tstamp_save/...)
    # ist save_buffer_size gross und fuellt sich ~1:1 mit der Frame-Anzahl. Zu
    # klein -> IndexError bei Frame == save_buffer_size. Konvention: >= max_frames
    # (Repo nutzt ~max_frames*1.3). Verhindert die Wiederholung des 1300-vom-Slice-Bugs.
    _sbs = int(base["frontend"]["save_buffer_size"])
    _maxf = int(base["dataset"]["max_frames"])
    if _sbs < _maxf:
        print(f"[FEHLER] save_buffer_size={_sbs} < max_frames={_maxf} im Template — "
              f"Tracker-Buffer overflowt. Auf >= {_maxf} (z.B. {round(_maxf*1.3)}) setzen.",
              file=sys.stderr)
        sys.exit(1)
    # Force the shared output dir for every variant; per-config save_dir would
    # scatter results otherwise.
    base["output"]["save_dir"] = SAVE_DIR
    # SelektionsUNABHAENGIGE Eval fuer JEDE Variante: Sim(3)-ATE + Held-out-
    # Novel-View-PSNR an fixen Frame-Positionen (jeder 20.) gegen GT. Macht den
    # Selektor-Vergleich fair (gleiches Eval-Set, Novel-View statt train-view).
    base["fair_eval"] = {
        "enabled": True,
        "eval_stride": EVAL_STRIDE,
        "gt_poses_file": "dji_poses_all_w2c.txt",
        "save_renders": True,
    }

    plan: list[tuple[str, str, dict]] = []

    # 1) baseline: VINGS internal motion-filter only
    plan.append(("baseline", "vings_filter", slice_gen.patch_baseline(base)))

    # 2) mapskip
    for n in slice_gen.SKIP_VALUES:
        plan.append(("mapskip", f"mapskip_{n}", slice_gen.patch_mapskip(base, n)))

    # 3) skip_no_filter
    for n in slice_gen.SKIP_VALUES:
        plan.append(("skip_no_filter", f"nofilter_skip_{n}",
                     slice_gen.patch_skip_no_filter(base, n)))

    # 4) selectors (default first, then variants)
    for sel, short in slice_gen.SELECTOR_FOLDER.items():
        plan.append((short, short, slice_gen.patch_selector(base, sel)))
        for suffix, override in slice_gen.SELECTOR_VARIANTS.get(sel, {}).items():
            plan.append((short, f"{short}_{suffix}",
                         slice_gen.patch_selector(base, sel, override)))

    print(f"\n=== amtown03 full_6199f — {len(plan)} configs ===")
    for group, variant, cfg in plan:
        path = TARGET_ROOT / group / f"{NAME_PREFIX}_{variant}.yaml"
        header = (
            f"# Auto-generated by scripts/gen_full_6199f_configs.py — DO NOT EDIT.\n"
            f"# dataset = amtown03 (full sequence, frames 0..6198)\n"
            f"# group   = {group}\n"
            f"# variant = {variant}\n"
        )
        slice_gen.write_yaml(path, cfg, header)
        print(f"  {path.relative_to(REPO)}")


if __name__ == "__main__":
    main()
